server:
  port: 8787
  servlet:
    context-path: /capisce-web
dubbo:
  application:
    name: capisce-web
  registry:
    address: zookeeper://127.0.0.1:20181
spring:
  application:
    name: capisce-web
  main:
    allow-bean-definition-overriding: true